---
#
# Endeca Tools and Frameworks
# This role should be run with sudo=yes sudo_user={{ install_user }}.
#

- set_fact:
    install_archive: "V46389-01.zip"
    install_executable: "cd/Disk1/install"

- name: temporary directory for install
  register: mktemp
  command: mktemp -d

- name: download installation archive
  get_url:
  args:
    url: "{{ install_archive_url }}"
    dest: "{{ playbook_dir }}/{{ install_archive }}"
  when: install_archive_url is defined

- name: expand toolsandframeworks archive
  unarchive: 
    src="{{ install_archive }}"
    dest="{{ mktemp.stdout }}"
    creates="{{ mktemp.stdout }}/{{ install_executable }}"

- name: create inventory directory for oracle universal installer
  file:
  args:
    state: directory
    path: "/u01/app/oraInventory"
    owner: oracle
    group: dba
    mode: 0755
  sudo: yes
  sudo_user: root

- name: Install Tools and Frameworks
  command: "{{ mktemp.stdout }}/{{ install_executable }}/silent_install.sh {{ mktemp.stdout }}/{{ install_executable }}/silent_response.rsp ToolsAndFrameworks {{ install_root }}/ToolsAndFrameworks {{ endeca_admin_password }}"
  args:
    creates: "{{ install_root }}/ToolsAndFrameworks"

# Disabling for now. Appears to allow login via the sso server but breaks back-end things like initialize-services. Need to figure out why.
#- name: setup for sso
#  lineinfile:
#    dest="{{ install_root }}/ToolsAndFrameworks/{{ endeca_toolsandframeworks_version }}/server/workspace/conf/webstudio.properties"
#    regexp="{{ item.name }}="
#    insertafter="Commerce SSO Authentication"
#    line="{{ item.name }}={{ item.value }}"
#  with_items:
#    - { name: "com.endeca.webstudio.useSSO", value: "true" }
#    - { name: "com.endeca.webstudio.sso.loginURL", value: "http://localhost:28840/sso/login" }
#    - { name: "com.endeca.webstudio.sso.controlURL", value: "http://localhost:28840/sso/control" }
#    - { name: "com.endeca.webstudio.sso.logoutURL", value: "http://localhost:28840/sso/logout" }
#    - { name: "com.endeca.webstudio.sso.validationURL", value: "http://localhost:28840/sso/validate" }
#    - { name: "com.endeca.webstudio.sso.keepAliveURL", value: "http://localhost:28840/sso/keepAlive" }
#    - { name: "com.endeca.webstudio.sso.keepAliveFrequency", value: "1800" }

# /app/oracle/product/endeca/ToolsAndFrameworks/11.1.0/credential_store/bin/manage_credentials.sh add --key ifcr --user admin --type password

- include: init.yml tags=configure_service sudo_user=root

#- name: clean up temporary directory
#  file: 
#    state=absent 
#    path="{{ mktemp.stdout }}"
